### ISSUE TITLE
With html: true, HTML escaping differ from embedded HTML escaping

### ISSUE THREAD

**Issue by Lucas-C** [markdown-it/markdown-it-container#11]
Hi.

I'm not sure if this is a bug, but this behaviour surprised me.

There are some reproduction steps:
```
$ cat repro.js
#!/usr/bin/env node
require('fs').readFile(process.argv[2], 'utf8', function (err, input) {
  var md = require('markdown-it')({html: true})
    .use(require('markdown-it-container'), 'container');
  process.stdout.write(md.render(input));
});

$ cat test.md
<div class="embedded-html">
A: "
</div>
<div class="embedded-html">
B: \"
</div>
<div class="embedded-html">
C: \\"
</div>

::: container
A: "
:::
::: container
B: \"
:::
::: container
C: \\"
:::

$ ./repro.js test.md
<div class="embedded-html">
A: "
</div>
<div class="embedded-html">
B: \"
</div>
<div class="embedded-html">
C: \\"
</div>
<div class="container">
<p>A: &quot;</p>
</div>
<div class="container">
<p>B: &quot;</p>
</div>
<div class="container">
<p>C: \&quot;</p>
</div>

```

It looks like when `markdown-it` `html: true` parameter is used, `div`s generated by `markdown-it-container` HTML escape their content one more time than `div` s "simply" embedded as HTML code.

Do you think `markdown-it-container` could avoid this extra-escaping ? Maybe by detecting if `html: true` is set ?

**Comment by puzrin** [comment]
Seems you've missed empty line after first `<div>`. See spec. That's a very common mistake.

**Comment by puzrin** [comment]
I don't see double escaping problem. After you add new line, result should be the same.

If i missed something - add details please.

**Comment by Lucas-C** [comment]
Got it: http://spec.commonmark.org/0.27/#example-118
Thank you !
