### ISSUE TITLE
Hints at how to fork for inline and custom labels needed.

### ISSUE THREAD

**Issue by cougarten** [markdown-it/markdown-it-container#14]
Hi,
I'm trying to make pretty sidenotes. To get by with just CSS I need something like the following behaviour (I just invented some markup):

- not just a [^1] as an indicator for a sidenote, but a section of the text (like a link has link-text)
- the actual sidenote inline

```
My text has [pretty *sidenotes*](^pretty_sidenote) inline.

[^pretty_sidenote]: 
  # I am a big sidenote
```

parsing to:

```
<p>
  My text has <span class="sidenote_text">pretty <b>sidenotes</b><div class="sidenote">
    <h1>I am a big sidenote</h1>
  </div> inline.
</p>
```

Now my troubles: 

- This plugin relies heavily on character positions at the beginning of the [^...] tag, I don't know how to add the second argument ("link"-text)
- I'm not sure when the actual markdown parsing happens where
- I could live without markdown in the "link-text"

I'm actually close to attempting to hack together some [insert_sidenote_open_tag] and search+replace it with html and than do the sidenote via js :/
Or use the bigfoot.js and try to adapt it to permanently visible sidenotes.

Here some dirty working sidenotes I made (with some other markdown parser): http://malea.lacerta.uberspace.de/quickup/testi/

They don't support markdown though and they have to be written inline...

Thanks for the help and the library itself!

**Comment by puzrin** [comment]
First, i don't recommend to reinvent custom markup :) . Second, if you still need it, and wish to have markup inside sidenotes, i'd recommend to avoid inline markup.

Something like https://github.com/markdown-it/markdown-it-container should work well.

Other plugins to investigate can be:

- https://github.com/markdown-it/markdown-it-deflist
- https://github.com/markdown-it/markdown-it-footnote
- https://github.com/markdown-it/markdown-it-abbr

I would use `markdown-it-container` approach to keep things simple.
