### ISSUE TITLE
how could I custome the tag name

### ISSUE THREAD

**Issue by scil** [markdown-it/markdown-it-container#16]
I want to control the tag name of rendered html, e.g. z-deep/section instead of div.

```
        .use(require('markdown-it-container'), 'decorate' , {
            validate: function(params) {
                return params.trim().match(/^(z-deep|section)$/);
            },

            render: function (tokens, idx) {
                var m = tokens[idx].info.trim().match(/^(z-deep|section)$/);

                var tag=m[1]||'div';

                if (tokens[idx].nesting === 1) {
                    // opening tag

                    return '<' + tag  + ' >\n';

                } else {
                    // closing tag
                    console.log('tag ',tag)
                    return '</'+tag+'>\n';
                }
            }
```

but the closing tag always is 'div', for example
```
::: z-deep
ok
:::
```
output:
```
<z-deep>
<p>ok</p>
</div>
```

**Comment by puzrin** [comment]
Your regexp doesn't match closing tag and you use div then. You can add `console.log` to renderer and see what happens.

**Comment by m4rrc0** [comment]
Hey, sorry to bring back this old thread but I tried to do the same and this question is not resolved. @puzrin , your response explains why the code does not work but is not an answer to the initial question.

The underlying problem to achieving tag customization seems to be that the closing tag does not have access to the opening token's information. So whatever we do on the opening tag thanks to the `info` data has no repercussion on the closing token.

Is there a way get the data from the opening token when we traverse the closing one?

**Comment by puzrin** [comment]
> Is there a way get the data from the opening token when we traverse the closing one?

In this implementation - no. Info string is passed only to opening token https://github.com/markdown-it/markdown-it-container/blob/master/index.mjs#L118. The renderer function is the same for both, but you can assign separate ones manually after plugin install.

**Comment by m4rrc0** [comment]
Thanks for the reply @puzrin .
I am working around this for the moment but will probably come back to it later.

Isn't there any link being made between the opening and closing token? Surely there is or the output wouldn't be rendered properly, especially when nesting containers inside each others.

I noticed the `map` property on the opening token which seems to detect the line number of the closing token but it does not make its `idx` predictable, right? Is there a way to get the `idx` of the closing token when traversing the opening one?

Or maybe there is just another plugin that you know of that is more suitable to accomplish this?

**Comment by puzrin** [comment]
Tokens are not a DOM; they are a lower abstraction layer, a simple flat array. You can only scan to the nearest with the same `.level`, that will be the pair.

Take a look at https://github.com/markdown-it/markdown-it-for-inline. It does not make what you need, but it can give you some ideas.

**Comment by m4rrc0** [comment]
Thanks a lot for the pointer @puzrin .

I'll try and post an update here if I come up with something related to this issue.
