### ISSUE TITLE
plugin not functioning

### ISSUE THREAD

**Issue by indiamcq** [markdown-it/markdown-it-container#18]
I am using @**noraesae/pen** so I can see the markdown-it rendered in a browser window. I added 3 plugins to the system: markdown-it-footnotes, markdown-it-attrs, and markdown-it-container. The first two work fine but the container one does not work at all. I added the required line   .use(require('markdown-it-container'), 'div') as the others are working it seems like it should work but does not for some reason. 
Also how do I specify a different markup character? Like this .use(require('markdown-it-container'), 'div', '~'). Your example is more complex and does not help me.
It may not be a container problem but seems to be since the others work.
Installed markdown-it plugins that come preinstalled with **pen** are: anchor, checkbox, emoji, highlightjs maybe there is a conflict with one of these but that seems unlikely.

Any thoughts?

Ian

**Comment by puzrin** [comment]
No idea, sorry. There are example in readme, working code in test directory and working demo for markdown-it. Just copy carefully from any place. If that doesn't help - create a test repo with minimal possible example and post the link.
