### ISSUE TITLE
Paragraph **p** surround image

### ISSUE THREAD

**Issue by NickNaso** [markdown-it/markdown-it-container#19]
Hi everyone,
below I report my configurations:

```js
// ...
const markdownItAttrs = require('markdown-it-attrs')
const markDownItContainer = require('markdown-it-container')
var blockImagePlugin = require("markdown-it-block-image")
const Markdown = require('markdown-it')({
    html: true,
    breaks: true,
    typographer: true,
    linkify: true
})
.use(markdownItAttrs)
.use(blockImagePlugin)
.use(markDownItContainer, 'htmlblock')
// ...
```
When I render my web page:

```html
<!DOCTYPE html>
<html>
    <body>
    <h1>My First Heading</h1>
    <p>My first paragraph.</p>
    {% markdown %}
    ::: htmlblock {.red} 
    ![img](img.png)
    ::: 
    {% endmarkdown %}
    </body>
</html>
```
I get that image will be surrounded by tag **p** 

```html
<html>
<head>
</head>
<body>
    <h1>My First Heading</h1>
    <p>My first paragraph.</p>
    <div class="htmlblock">
        <p>
             <img src="img.png" alt="img">
      </p>
    </div>
</body>
</html>
```
Is this normal or I did something wrong? Is there a method to avoid this behavior?

Thanks a lot.

**Comment by puzrin** [comment]
That's normal. This module is a container to wrap internal markdown content. If you try content standalone, you will get [the same result](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22!%5Bimg%5D%28img.png%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D), with `<p>`.

If you don't need `<p>`, you should not use markdown - use html of modified fenced block.

**Comment by xgz123** [comment]
`div` seems to be a better option ?
