### ISSUE TITLE
How to use in browser

### ISSUE THREAD

**Issue by syarul** [markdown-it/markdown-it-container#2]
How to use this in browser instead using require module. I try this but doesn't seem to work

```javascript
var container = window.markdownitContainer;
md.use(container);
```

**Comment by puzrin** [comment]
It should work. Try to create a demo example.

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/commit/404c78290a4d275492be4d2a809328da95f75c98 i think you missed plugin options. That's not browser-related issue. Make sure it works in node first.

**Comment by syarul** [comment]
Yeah I got it working by adding the class option

```javascript
md.use(container, 'tab')
```

Sorry this maybe a different question,
still figuring out how to handle multiple nested class, ```lasttab``` will the child of  ```anothertab``` but how make it child of  ```tab```?

```markdown
::: tab
::: anothertab
:::lasttab
content
:::
```

**Comment by puzrin** [comment]
Add more :::::: to outer block. Nesting is the same as for fenced blocks.

http://spec.commonmark.org/0.22/#fenced-code-blocks

**Comment by syarul** [comment]
oh thanks @puzrin that save me a lot!

**Comment by puzrin** [comment]
[example](http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3A%3A%3A%3A%20warning%5Cnouter%5Cn%3A%3A%3A%20warning%5Cninner%5Cn%3A%3A%3A%5Cn%3A%3A%3A%3A%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by isTravis** [comment]
This is amazingly helpful and not necessarily obvious from the README if you don't know the commonmark specification of fenced blocks. 

It may be useful for others to have a quick note (and perhaps link to the example) describing nested containers.

Thanks for all your work on this plugin!
