### ISSUE TITLE
Multiline complex container?

### ISSUE THREAD

**Issue by chris-dura** [markdown-it/markdown-it-container#25]
Hello, I've looked through the documentation, and I'm having a hard time figuring out how to do what I need. I think part of the problem is that the [example](https://github.com/markdown-it/markdown-it-container#example) only works when the markdown is all on a singleline, but the other example is on multilines:
```md
::: warning
*here be dragons*
:::
```

Basically, with the following:
```md
::: warning
## Beware!
*here be dragons*
_seriously, there are._
:::
```
I'd like to render out the following HTML:
```html
<div class="warning">
  <div class="left-col"><h2>Beware!</h2></div>
  <div class="middle"><em>here be dragons</em></div>
  <div class="right"><em>seriously, there are.</em></div>
</div>
```

**Comment by chris-dura** [comment]
It seems that when passing a multiline the `tokens[idx].info` only has the first line, and not the content of the container...

**Comment by puzrin** [comment]
If you need nesting:

```
::: warning
:::::: left-col
::::::
:::::: middle
::::::
:::::: right
::::::
:::
```

Principle is the same as with fenced blocks - vary delimiter length.
