### ISSUE TITLE
feature: Container Ids

### ISSUE THREAD

**Issue by LukeTOBrien** [markdown-it/markdown-it-container#28]
Hello there,

I would like to add ids to my containers, but at the moment only classes can be added.  
The syntax I would like to use is a hash (`#`) followed by the id, like so:

``` Markdown
::: #container
:::
```
However this currently renders as a class rather than the id as I would like.

``` HTML
<div class="#container">
</div>
```
This is what I would like:

``` HTML
<div id="container">
</div>
```

How easy would this feature be to add and do you this is would be a useful addition?

**Comment by puzrin** [comment]
Just override default renderer function with your own.
