### ISSUE TITLE
How to nest with the same marker?

### ISSUE THREAD

**Issue by SpoinkyNL** [markdown-it/markdown-it-container#33]
Hi, this example given in #25 doesn't work because the markers are the same. Only left-col is placed inside the warning div. 

```
::: warning
:::: left-col
::::
:::: middle
::::
:::: right
::::
:::
```

Results in:
``` html
<div class="warning">
    <div class="left-col"></div>
</div>
<div class="middle"></div>
<div class="right"></div>
<p>:::</p>
```

Is the only correct way to do this by giving left-col, midlde and right different markers? This makes for very messy markdown.

**Comment by puzrin** [comment]
[link](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3A%3A%3A%3A%3A%20warning%5Cn%2Ahere%20be%20dragons%2A%5Cn%3A%3A%3A%3A%20warning%5Cn123%5Cn%3A%3A%3A%3A%5Cn%3A%3A%3A%3A%3A%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)

```
::::: warning
*here be dragons*
:::: warning
123
::::
:::::
```

Outer marker should be bigger. See CM spec for fenced blocks
