### ISSUE TITLE
Specify multiple container names?

### ISSUE THREAD

**Issue by mikelhamer** [markdown-it/markdown-it-container#38]
I would like configure multiple container names to all use the default renderer. I am able to accomplish this with
```
md.use(require('markdown-it-container'), 'container-1');
md.use(require('markdown-it-container'), 'container-2');
```
Is there any downside to calling the require method more than once like this?

I am wondering if there is a simpler way. Maybe something like this?

`md.use(require('markdown-it-container'), ['container-1', container-2']));`

**Comment by puzrin** [comment]
There are no need to "improve" working things :)

**Comment by mikelhamer** [comment]
> There are no need to "improve" working things :)

So there is nothing wrong with calling the same require method over and over again for every customer container?

**Comment by puzrin** [comment]
Yes. Or you can create temporary var if you wish.
