### ISSUE TITLE
Add option to omit content output

### ISSUE THREAD

**Issue by alxmagro** [markdown-it/markdown-it-container#47]
I was trying to use `markdown-it-container` for get block content and render myself with some transformations, and I could append it to "opening tag" return, but the content is still rendering on output.

Aside "validate", "render" and "marker", it could have option to omit output (eg.: "output: false").

It give more options to dev, to do thigs like I described above.

**Comment by alkaitagi** [comment]
Yes, it'd be ready helpful. In my project I wrap a container around a table, then on container rendering I parse the table's data and pass it into a custom Vue component. Since I no longer need the original table I've ended up just wrapping the content in `<!--` comments.

**Comment by KaelWD** [comment]
You can iterate `tokens` until you find one with `type: 'container_<name>_close'` and remove all tokens between that and the open one.

**Comment by puzrin** [comment]
This does not look like intended use

1. You probably need custom fenced block instead, for raw content access
2. Or you can call `.parse` manually, then update tokens as needed, then call render.
