### ISSUE TITLE
this doesn't appear to work anymore.

### ISSUE THREAD

**Issue by ambrooks** [markdown-it/markdown-it-container#5]
I'm using markdown-it v6.0.1 and I copied your "spoiler" example verbatim. It looks like this plugin no longer works.

**Comment by puzrin** [comment]
This plugin works and exists in demo. [Example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%23%23%20%5BCustom%20containers%5D%28https%3A%2F%2Fgithub.com%2Fmarkdown-it%2Fmarkdown-it-container%29%5Cn%5Cn%3A%3A%3A%20warning%5Cn%2Ahere%20be%20dragons%2A%5Cn%3A%3A%3A%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by julianomoreira** [comment]
I'm having a hard time getting this to work too. Has anything changed?

**Comment by puzrin** [comment]
If you have a problem, the best way to ask for help is to create test repo with demo. It's impossible to help with reports "everything broken, plugin sucks" :). Such issues are closed as not useful (with the factthat you can see this plugin working in markdown-it demo).

**Comment by julianomoreira** [comment]
Sorry. Yes. I'll do that. Thanks!

**Comment by sidorares** [comment]
does not work for me as well. Also on linked demo if you edit "warning" class result appear without transformation

![screen shot 2016-05-21 at 9 21 39 pm](https://cloud.githubusercontent.com/assets/173025/15448096/4ac0684a-1f9a-11e6-93b3-1b0596d4531a.png)

**Comment by puzrin** [comment]
Hi @sidorares :)

> does not work for me as well.

Need code example.

> Also on linked demo if you edit "warning" class result appear without transformation

That's intended. `:::` defines a possible wrapper of unknown type, and each type is defined with name. Something like fenced code block with language name.

If no appropriate wrapper type found (by name) - we don't know how to present it, and do nothing. You can change is, if you wish, by providing your own validator. You can even force it to look as fenced block, but do something special when "reserved" name used.

**Comment by puzrin** [comment]
Adding CSS class is just a minimal default for demo, don't consider is as main feature. Key points are:

- check if we need to wrap at all (by opening tag + following header)
- if yes, then render nested content & wrap it with something custom.

**Comment by sidorares** [comment]
```js
var md = require('markdown-it')({})
 .use(require('markdown-it-container'));

console.log(md.render(`
::: class-name
  test1 **test2** test3
:::
`));
```

Output:

```
<p>::: class-name
test1 <strong>test2</strong> test3
:::</p>
```

**Comment by sidorares** [comment]
> If no renderer defined, \<div\> with container name class will be created:

Based on readme I'd expect to see something like

```html
<p><div class="class-name">
test1 <strong>test2</strong> test3
</div></p>
```

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it-container#api

You've missed plugin params, `name` it's mandatory (that's like namespace for multiple `.use()` of this plugin, see src).

By default `name` is required in markup, but you can override validator https://github.com/markdown-it/markdown-it-container/blob/2.0.0/index.js#L8-L10

**Comment by sidorares** [comment]
What does it mean and why it's mandatory?

```js
var md = require('markdown-it')({})
 .use(require('markdown-it-container')({ name: 'foobar'}));

console.log(md.render(`
::: class-name
  test1 **test2** test3
:::
`));
```

now fails with `TypeError: Cannot read property 'ruler' of undefined
    at container_plugin (./node_modules/markdown-it-container/index.js:138:11)`

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it-container#example

```js
var md = require('markdown-it')()
  .use(
    require('markdown-it-container'), // plugin
    'foobar', // plugin param1, mandatory
    { // plugin param2
      validate: name => name.trim().length // allow everything not empty (by i don't recommend)
    }
  );
```

**Comment by sidorares** [comment]
This is something I expected as default behaviour:

```js
var md = require('markdown-it')({})
 .use(require('markdown-it-container'), 'classname', {
  validate: name => name.trim().length,
  render: (tokens, idx) => {
    if (tokens[idx].nesting === 1) {
      return `<div class="${tokens[idx].info.trim()}">\n`;
    } else  {
      return '</div>\n';
    }
  }
});

console.log(md.render(`
::: test1
test1 **test2** test3
:::
`));
```

```html
<div class="test1">
<p>test1 <strong>test2</strong> test3</p>
</div>
```

Also I could not get nested containers to work, `nesting` is either 1 or -1. How do I make this

```md
::: test1
::: test2
test1 **test2** test3
:::
:::
```

transform into 
```html
<div class="test1">
<div class="test2">
<p>test1 <strong>test2</strong> test3</p>
</div>
</div>
```
?

**Comment by puzrin** [comment]
Nesting should work the same way as with fenced blocks. Add more `:::::::::::::::` for outer blocks

```md
:::: test1
::: test2
test1 **test2** test3
:::
::::
```

**Comment by sidorares** [comment]
Thanks @puzrin !
