### ISSUE TITLE
Feature: Add title to container block

### ISSUE THREAD

**Issue by alinex** [markdown-it/markdown-it-container#8]
I'd like to have an optional title text:

    ::: info Tips and Tricks
    You may....
    :::

This should be transformed to:

    <div class="info">
    <header>Tips and Tricks</header>
    <p>You may...</p>
    </div>

If no title given it should behave like now.

**Comment by puzrin** [comment]
Customize the renderer as in readme example.

**Comment by alinex** [comment]
Thanks, that works great for me.
